name: shell Salim Commands,

on: [push]
jobs:
  run-Salim-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a name
        run: echo "Hello world"
      - name: multiline script
        run: |
          node -v 
          npm -v
      - name: python Command
        run: |
          import platform
          print(platform.processor())

        shell: python
